-- Realocacao de centro de custo, etapa 2: tabelas do historico e reserva de saldo.
-- Pagamentos e recebimentos usam as mesmas tabelas (coluna modulo); o pedido_id nao tem FK porque aponta para duas tabelas.
--
-- realocacoes       = uma solicitacao (quem pediu, quando, quem decidiu). Fluxo 3 grava ja 'Autorizada', sem autorizador.
-- realocacao_itens  = a distribuicao: lado 'antes' (copia das linhas do fluxo do pedido) e 'depois' (a proposta), por centro/categoria/
--                     mes/beneficiario. Fluxo 3 nao tem mes: mes/ano ficam NULL e a distribuicao e so sobre o total.
--
-- Saldo travado: enquanto a realocacao esta 'Aguardando Autorizacao', o que ENTRA a mais em cada centro/categoria/mes (depois - antes,
-- so a parte positiva) soma no consumo do orcamento, como um pedido pendente. O que sai da origem so libera ao aplicar.
-- Recusar ou autorizar tira a reserva sozinho (a view so olha as pendentes); quem autoriza troca as linhas do fluxo na mesma transacao.

CREATE TABLE public.realocacoes (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  projeto_id       integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id),
  modulo           text NOT NULL CHECK (modulo IN ('pagamentos', 'recebimentos')),
  pedido_id        bigint NOT NULL,
  status           text NOT NULL DEFAULT 'Aguardando Autorização' CHECK (status IN ('Aguardando Autorização', 'Autorizada', 'Recusada')),
  modo             text NOT NULL CHECK (modo IN ('percentual', 'valor')),
  solicitante      text NOT NULL,
  data_solicitacao timestamptz NOT NULL DEFAULT now(),
  autorizador      text,
  data_decisao     timestamptz,
  observacao       text
);

-- um pedido so tem uma realocacao pendente por vez
CREATE UNIQUE INDEX realocacoes_uma_pendente ON public.realocacoes (modulo, pedido_id) WHERE status = 'Aguardando Autorização';
CREATE INDEX realocacoes_pedido_idx ON public.realocacoes (modulo, pedido_id);

CREATE TABLE public.realocacao_itens (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  realocacao_id bigint NOT NULL REFERENCES public.realocacoes(id) ON DELETE CASCADE,
  projeto_id    integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id),
  lado          text NOT NULL CHECK (lado IN ('antes', 'depois')),
  empresa       text NOT NULL,
  categoria     text NOT NULL,
  mes           integer,
  ano           integer,
  beneficiario  text,
  valor         numeric(15,2) NOT NULL CHECK (valor >= 0)
);
CREATE INDEX realocacao_itens_realocacao_idx ON public.realocacao_itens (realocacao_id);

-- Reserva por chave do orcamento. security_invoker: respeita o RLS de quem consulta.
CREATE VIEW public.realocacao_reservas WITH (security_invoker = true) AS
SELECT projeto_id, modulo, empresa, categoria, mes, ano, SUM(delta) AS valor
FROM (
  SELECT r.projeto_id, r.modulo, i.empresa, i.categoria, i.mes, i.ano,
         GREATEST(SUM(CASE i.lado WHEN 'depois' THEN i.valor ELSE -i.valor END), 0) AS delta
  FROM public.realocacoes r
  JOIN public.realocacao_itens i ON i.realocacao_id = r.id
  WHERE r.status = 'Aguardando Autorização' AND i.mes IS NOT NULL
  GROUP BY r.id, r.projeto_id, r.modulo, i.empresa, i.categoria, i.mes, i.ano
) d
WHERE delta > 0
GROUP BY projeto_id, modulo, empresa, categoria, mes, ano;

-- O recalculo do orcamento (2026-10-06_orcamento_recalculo.sql) passa a somar a reserva.
-- A view tem no maximo 1 linha por chave, entao MAX(r.valor) so traz o valor dela.
CREATE OR REPLACE FUNCTION public.atualizar_valor_pedidos_solicitados() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE controle_orcamento co
    SET valor_pedidos_solicitados = t.total
    FROM (
        SELECT c.id, COALESCE(SUM(psf.valor_referente), 0) + COALESCE(MAX(r.valor), 0) AS total
        FROM controle_orcamento c
        LEFT JOIN pedidos_solicitados_fluxo psf
          ON psf.projeto_id = c.projeto_id AND psf.empresa = c.empresa AND psf.categoria = c.categoria
         AND psf.mes = c.mes AND psf.ano = c.ano
         AND psf.status NOT IN ('Não Autorizado', 'Cancelado')
        LEFT JOIN realocacao_reservas r
          ON r.modulo = 'pagamentos' AND r.projeto_id = c.projeto_id AND r.empresa = c.empresa AND r.categoria = c.categoria
         AND r.mes = c.mes AND r.ano = c.ano
        GROUP BY c.id
    ) t
    WHERE co.id = t.id AND co.valor_pedidos_solicitados IS DISTINCT FROM t.total;

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.atualizar_valor_pedidos_solicitados_receita() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE controle_orcamento_receita co
    SET valor_pedidos_solicitados = t.total
    FROM (
        SELECT c.id, COALESCE(SUM(psf.valor_referente), 0) + COALESCE(MAX(r.valor), 0) AS total
        FROM controle_orcamento_receita c
        LEFT JOIN pedidos_solicitados_fluxo_receita psf
          ON psf.projeto_id = c.projeto_id AND psf.empresa = c.empresa AND psf.categoria = c.categoria
         AND psf.mes = c.mes AND psf.ano = c.ano
         AND psf.status NOT IN ('Não Autorizado', 'Cancelado')
        LEFT JOIN realocacao_reservas r
          ON r.modulo = 'recebimentos' AND r.projeto_id = c.projeto_id AND r.empresa = c.empresa AND r.categoria = c.categoria
         AND r.mes = c.mes AND r.ano = c.ano
        GROUP BY c.id
    ) t
    WHERE co.id = t.id AND co.valor_pedidos_solicitados IS DISTINCT FROM t.total;

    RETURN NULL;
END;
$$;

-- Qualquer mudanca nas realocacoes (criar, decidir, apagar) recalcula o orcamento dos dois modulos.
CREATE TRIGGER trigger_realocacoes_orcamento AFTER INSERT OR UPDATE OR DELETE ON public.realocacoes
  FOR EACH STATEMENT EXECUTE FUNCTION public.atualizar_valor_pedidos_solicitados();
CREATE TRIGGER trigger_realocacoes_orcamento_receita AFTER INSERT OR UPDATE OR DELETE ON public.realocacoes
  FOR EACH STATEMENT EXECUTE FUNCTION public.atualizar_valor_pedidos_solicitados_receita();
CREATE TRIGGER trigger_realocacao_itens_orcamento AFTER INSERT OR UPDATE OR DELETE ON public.realocacao_itens
  FOR EACH STATEMENT EXECUTE FUNCTION public.atualizar_valor_pedidos_solicitados();
CREATE TRIGGER trigger_realocacao_itens_orcamento_receita AFTER INSERT OR UPDATE OR DELETE ON public.realocacao_itens
  FOR EACH STATEMENT EXECUTE FUNCTION public.atualizar_valor_pedidos_solicitados_receita();

-- RLS igual as demais tabelas de dados: so o projeto ativo do usuario.
ALTER TABLE public.realocacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY rls_projeto ON public.realocacoes FOR ALL TO anon, authenticated
  USING (projeto_id = (SELECT public.app_projeto_rls()))
  WITH CHECK (projeto_id = (SELECT public.app_projeto_rls()));
ALTER TABLE public.realocacao_itens ENABLE ROW LEVEL SECURITY;
CREATE POLICY rls_projeto ON public.realocacao_itens FOR ALL TO anon, authenticated
  USING (projeto_id = (SELECT public.app_projeto_rls()))
  WITH CHECK (projeto_id = (SELECT public.app_projeto_rls()));
