-- MULTI-PROJETO, FASE 1 (banco). Ver docs/plano-multiprojeto.md.
-- Cria projetos e usuarios_projetos, cadastra o projeto UBX (id 1) e liga todos os dados atuais a ele.
-- O sistema continua funcionando igual: sem cabecalho x-projeto-id, tudo cai no projeto 1.
-- Gerado por script; roda em uma unica transacao (se algo falhar, nada e alterado).
-- Rodar PRIMEIRO no banco de teste. Faca backup antes de rodar na producao.

BEGIN;

-- 1. Projetos e vinculos --------------------------------------------------------------------
CREATE TABLE public.projetos (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome      text    NOT NULL UNIQUE,
  ativo     boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.projetos (id, nome) VALUES (1, 'UBX');
SELECT setval(pg_get_serial_sequence('public.projetos', 'id'), 1);

CREATE TABLE public.usuarios_projetos (
  usuario_id bigint  NOT NULL REFERENCES public.usuarios(id)  ON DELETE CASCADE,
  projeto_id integer NOT NULL REFERENCES public.projetos(id)  ON DELETE CASCADE,
  papel      text    NOT NULL CHECK (papel IN ('admin', 'user')),
  PRIMARY KEY (usuario_id, projeto_id)
);
-- Todo usuario atual entra no UBX, com o papel que ja tem (owner e admin = admin).
INSERT INTO public.usuarios_projetos (usuario_id, projeto_id, papel)
SELECT id, 1, CASE WHEN hierarquia::text IN ('owner', 'admin') THEN 'admin' ELSE 'user' END FROM public.usuarios;

-- 2. Projeto ativo (vem do cabecalho HTTP x-projeto-id) -------------------------------------
-- nullif(...,''): depois de uma transacao o Postgres deixa o parametro como texto vazio, nao NULL.
CREATE FUNCTION public.app_projeto_ativo() RETURNS integer LANGUAGE sql STABLE AS $$
  SELECT nullif(nullif(current_setting('request.headers', true), '')::json ->> 'x-projeto-id', '')::integer
$$;
-- Valor padrao do projeto_id. O "1" e temporario (fase 4 remove): sem cabecalho, cai no UBX.
CREATE FUNCTION public.app_projeto_default() RETURNS integer LANGUAGE sql STABLE AS $$
  SELECT coalesce(public.app_projeto_ativo(), 1)
$$;

-- 3. Coluna projeto_id nas tabelas raiz (dados atuais viram UBX) -----------------------------
ALTER TABLE public.empresas ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.categorias ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.categorias_receita ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.fornecedores ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.clientes ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.orcamentos_usuarios ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.orcamentos_usuarios_receita ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.controle_orcamento ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.controle_orcamento_receita ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.registro_orcamentos ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.registro_orcamentos_receita ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.registro_orcamento_analise ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.registro_orcamento_analise_receita ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.pedidos_solicitados ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.pedidos_solicitados_receita ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.pedidos_solicitados_fluxo ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.pedidos_solicitados_fluxo_receita ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.requisicoes ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.requisicoes_receita ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.conta_pagador ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.conta_receita ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.modelo_contrato ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.modelo_contrato_venda ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.controle_sequencial ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.controle_sequencial_recebimento ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
ALTER TABLE public.config ADD COLUMN projeto_id integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id);
CREATE INDEX idx_pedidos_solicitados_projeto ON public.pedidos_solicitados (projeto_id);
CREATE INDEX idx_pedidos_solicitados_receita_projeto ON public.pedidos_solicitados_receita (projeto_id);
CREATE INDEX idx_pedidos_solicitados_fluxo_projeto ON public.pedidos_solicitados_fluxo (projeto_id);
CREATE INDEX idx_pedidos_solicitados_fluxo_receita_projeto ON public.pedidos_solicitados_fluxo_receita (projeto_id);

-- 4. Chaves: unicos e estrangeiras passam a incluir o projeto --------------------------------
-- 4a. Apaga as chaves estrangeiras antigas (por nome, sem projeto)
ALTER TABLE public.categorias DROP CONSTRAINT categorias_empresa_fkey;
ALTER TABLE public.categorias_receita DROP CONSTRAINT categorias_receita_empresa_fkey;
ALTER TABLE public.controle_orcamento DROP CONSTRAINT controle_orcamento_empresa_categoria_fkey;
ALTER TABLE public.controle_orcamento_receita DROP CONSTRAINT controle_orcamento_receita_empresa_categoria_fkey;
ALTER TABLE public.orcamentos_usuarios DROP CONSTRAINT orcamentos_usuarios_empresa_categoria_fkey;
ALTER TABLE public.orcamentos_usuarios_receita DROP CONSTRAINT orcamentos_usuarios_receita_empresa_categoria_fkey;
ALTER TABLE public.pedidos_solicitados DROP CONSTRAINT pedidos_solicitados_empresa_categoria_fkey;
ALTER TABLE public.pedidos_solicitados DROP CONSTRAINT pedidos_solicitados_fornecedor_fkey;
ALTER TABLE public.pedidos_solicitados_fluxo DROP CONSTRAINT pedidos_solicitados_fluxo_empresa_categoria_fkey;
ALTER TABLE public.pedidos_solicitados_fluxo DROP CONSTRAINT pedidos_solicitados_fluxo_fornecedor_fkey;
ALTER TABLE public.pedidos_solicitados_receita DROP CONSTRAINT pedidos_solicitados_receita_empresa_categoria_fkey;
ALTER TABLE public.pedidos_solicitados_receita DROP CONSTRAINT pedidos_solicitados_receita_cliente_fkey;
ALTER TABLE public.pedidos_solicitados_fluxo_receita DROP CONSTRAINT pedidos_solicitados_fluxo_receita_empresa_categoria_fkey;
ALTER TABLE public.pedidos_solicitados_fluxo_receita DROP CONSTRAINT pedidos_solicitados_fluxo_receita_cliente_fkey;
ALTER TABLE public.registro_orcamento_analise DROP CONSTRAINT registro_orcamento_analise_empresa_categoria_fkey;
ALTER TABLE public.registro_orcamento_analise_receita DROP CONSTRAINT registro_orcamento_analise_receita_empresa_categoria_fkey;
ALTER TABLE public.registro_orcamentos DROP CONSTRAINT registro_orcamentos_empresa_categoria_fkey;
ALTER TABLE public.registro_orcamentos_receita DROP CONSTRAINT registro_orcamentos_receita_empresa_categoria_fkey;
ALTER TABLE public.requisicoes DROP CONSTRAINT requisicoes_empresa_categoria_fkey;
ALTER TABLE public.requisicoes_receita DROP CONSTRAINT requisicoes_receita_empresa_categoria_fkey;
-- 4b. Troca os unicos
ALTER TABLE public.empresas DROP CONSTRAINT empresas_empresa_key;
ALTER TABLE public.categorias DROP CONSTRAINT categorias_empresa_categoria_unique;
ALTER TABLE public.categorias_receita DROP CONSTRAINT categorias_receita_empresa_categoria_unique;
ALTER TABLE public.fornecedores DROP CONSTRAINT fornecedores_nome_key;
ALTER TABLE public.clientes DROP CONSTRAINT clientes_nome_key;
ALTER TABLE public.controle_orcamento DROP CONSTRAINT controle_orcamento_unique_key;
ALTER TABLE public.controle_orcamento_receita DROP CONSTRAINT controle_orcamento_receita_unique_key;
ALTER TABLE public.orcamentos_usuarios DROP CONSTRAINT unique_orcamento_new;
ALTER TABLE public.orcamentos_usuarios_receita DROP CONSTRAINT unique_orcamento_receita_new;
ALTER TABLE public.config DROP CONSTRAINT config_chave_key;
ALTER TABLE public.empresas ADD CONSTRAINT empresas_empresa_key UNIQUE (projeto_id, empresa);
ALTER TABLE public.categorias ADD CONSTRAINT categorias_empresa_categoria_unique UNIQUE (projeto_id, empresa, categoria);
ALTER TABLE public.categorias_receita ADD CONSTRAINT categorias_receita_empresa_categoria_unique UNIQUE (projeto_id, empresa, categoria);
ALTER TABLE public.fornecedores ADD CONSTRAINT fornecedores_nome_key UNIQUE (projeto_id, nome);
ALTER TABLE public.clientes ADD CONSTRAINT clientes_nome_key UNIQUE (projeto_id, nome);
ALTER TABLE public.controle_orcamento ADD CONSTRAINT controle_orcamento_unique_key UNIQUE (projeto_id, empresa, categoria, mes, ano);
ALTER TABLE public.controle_orcamento_receita ADD CONSTRAINT controle_orcamento_receita_unique_key UNIQUE (projeto_id, empresa, categoria, mes, ano);
ALTER TABLE public.orcamentos_usuarios ADD CONSTRAINT unique_orcamento_new UNIQUE (projeto_id, empresa, categoria, mes, ano);
ALTER TABLE public.orcamentos_usuarios_receita ADD CONSTRAINT unique_orcamento_receita_new UNIQUE (projeto_id, empresa, categoria, mes, ano);
ALTER TABLE public.config ADD CONSTRAINT config_chave_key UNIQUE (projeto_id, chave);
-- controle_sequencial: uma sequencia por projeto
ALTER TABLE public.controle_sequencial DROP CONSTRAINT controle_sequencial_pkey;
ALTER TABLE public.controle_sequencial ADD CONSTRAINT controle_sequencial_pkey PRIMARY KEY (projeto_id, tipo);
ALTER TABLE public.controle_sequencial_recebimento DROP CONSTRAINT controle_sequencial_recebimento_pkey;
ALTER TABLE public.controle_sequencial_recebimento ADD CONSTRAINT controle_sequencial_recebimento_pkey PRIMARY KEY (projeto_id, tipo);
-- 4c. Recria as chaves estrangeiras incluindo projeto_id
ALTER TABLE public.categorias ADD CONSTRAINT categorias_empresa_fkey FOREIGN KEY (projeto_id, empresa) REFERENCES public.empresas(projeto_id, empresa) ON UPDATE CASCADE;
ALTER TABLE public.categorias_receita ADD CONSTRAINT categorias_receita_empresa_fkey FOREIGN KEY (projeto_id, empresa) REFERENCES public.empresas(projeto_id, empresa) ON UPDATE CASCADE;
ALTER TABLE public.controle_orcamento ADD CONSTRAINT controle_orcamento_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.controle_orcamento_receita ADD CONSTRAINT controle_orcamento_receita_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias_receita(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.orcamentos_usuarios ADD CONSTRAINT orcamentos_usuarios_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.orcamentos_usuarios_receita ADD CONSTRAINT orcamentos_usuarios_receita_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias_receita(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.pedidos_solicitados ADD CONSTRAINT pedidos_solicitados_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.pedidos_solicitados_fluxo ADD CONSTRAINT pedidos_solicitados_fluxo_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.pedidos_solicitados_receita ADD CONSTRAINT pedidos_solicitados_receita_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias_receita(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.pedidos_solicitados_fluxo_receita ADD CONSTRAINT pedidos_solicitados_fluxo_receita_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias_receita(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.registro_orcamento_analise ADD CONSTRAINT registro_orcamento_analise_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.registro_orcamento_analise_receita ADD CONSTRAINT registro_orcamento_analise_receita_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias_receita(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.registro_orcamentos ADD CONSTRAINT registro_orcamentos_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.registro_orcamentos_receita ADD CONSTRAINT registro_orcamentos_receita_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias_receita(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.requisicoes ADD CONSTRAINT requisicoes_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.requisicoes_receita ADD CONSTRAINT requisicoes_receita_empresa_categoria_fkey FOREIGN KEY (projeto_id, empresa, categoria) REFERENCES public.categorias_receita(projeto_id, empresa, categoria) ON UPDATE CASCADE;
ALTER TABLE public.pedidos_solicitados ADD CONSTRAINT pedidos_solicitados_fornecedor_fkey FOREIGN KEY (projeto_id, fornecedor) REFERENCES public.fornecedores(projeto_id, nome) ON UPDATE CASCADE;
ALTER TABLE public.pedidos_solicitados_fluxo ADD CONSTRAINT pedidos_solicitados_fluxo_fornecedor_fkey FOREIGN KEY (projeto_id, fornecedor) REFERENCES public.fornecedores(projeto_id, nome) ON UPDATE CASCADE;
ALTER TABLE public.pedidos_solicitados_receita ADD CONSTRAINT pedidos_solicitados_receita_cliente_fkey FOREIGN KEY (projeto_id, cliente) REFERENCES public.clientes(projeto_id, nome) ON UPDATE CASCADE;
ALTER TABLE public.pedidos_solicitados_fluxo_receita ADD CONSTRAINT pedidos_solicitados_fluxo_receita_cliente_fkey FOREIGN KEY (projeto_id, cliente) REFERENCES public.clientes(projeto_id, nome) ON UPDATE CASCADE;

-- 5. Funcoes e triggers de orcamento passam a considerar o projeto ---------------------------

-- Pagamentos
CREATE OR REPLACE FUNCTION public.atualiza_controle_orcamento() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
   INSERT INTO controle_orcamento (projeto_id, empresa, categoria, mes, ano, valor_orcamento)
   VALUES (NEW.projeto_id, NEW.empresa, NEW.categoria, NEW.mes, NEW.ano, NEW.valor_orcamento)
   ON CONFLICT (projeto_id, empresa, categoria, mes, ano)
   DO UPDATE SET valor_orcamento = EXCLUDED.valor_orcamento;
   RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.atualizar_valor_pedidos_solicitados() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE controle_orcamento co
    SET valor_pedidos_solicitados = (
        SELECT COALESCE(SUM(valor_referente), 0)
        FROM pedidos_solicitados_fluxo psf
        WHERE psf.projeto_id = co.projeto_id
          AND psf.empresa = co.empresa
          AND psf.categoria = co.categoria
          AND psf.mes = co.mes
          AND psf.ano = co.ano
          AND psf.status != 'Não Autorizado'
    )
    WHERE EXISTS (
        SELECT 1
        FROM pedidos_solicitados_fluxo psf
        WHERE psf.projeto_id = co.projeto_id
          AND psf.empresa = co.empresa
          AND psf.categoria = co.categoria
          AND psf.mes = co.mes
          AND psf.ano = co.ano
    );

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_valor_pedidos_solicitados() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE controle_orcamento co
  SET valor_pedidos_solicitados = (
    SELECT COALESCE(SUM(psf.valor_referente), 0)
    FROM pedidos_solicitados_fluxo psf
    WHERE psf.projeto_id = co.projeto_id
    AND psf.empresa = co.empresa
    AND psf.categoria = co.categoria
    AND CAST(psf.mes AS INTEGER) = CAST(co.mes AS INTEGER)
    AND CAST(psf.ano AS INTEGER) = CAST(co.ano AS INTEGER)
  )
  WHERE co.projeto_id = NEW.projeto_id
  AND co.empresa = NEW.empresa
  AND co.categoria = NEW.categoria
  AND CAST(co.mes AS INTEGER) = CAST(NEW.mes AS INTEGER)
  AND CAST(co.ano AS INTEGER) = CAST(NEW.ano AS INTEGER);

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_orcamento_analise() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
   registro_existente registro_orcamento_analise%ROWTYPE;
BEGIN
   SELECT * INTO registro_existente
   FROM registro_orcamento_analise
   WHERE projeto_id = NEW.projeto_id
   AND empresa = NEW.empresa
   AND categoria = NEW.categoria
   AND mes = NEW.mes
   AND ano = NEW.ano;

   IF FOUND THEN
       UPDATE registro_orcamento_analise
       SET valor_orcamento_vigente = NEW.valor_orcamento
       WHERE projeto_id = NEW.projeto_id
       AND empresa = NEW.empresa
       AND categoria = NEW.categoria
       AND mes = NEW.mes
       AND ano = NEW.ano;
   ELSE
       INSERT INTO registro_orcamento_analise (
           projeto_id, empresa, categoria, mes, ano, valor_orcamento_vigente, valor_orcamento_inicial
       )
       VALUES (
           NEW.projeto_id, NEW.empresa, NEW.categoria, NEW.mes, NEW.ano, NEW.valor_orcamento, NEW.valor_orcamento
       );
   END IF;

   RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_orcamentos_usuarios() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
   IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
       INSERT INTO orcamentos_usuarios (projeto_id, empresa, categoria, mes, ano, valor_orcamento)
       VALUES (NEW.projeto_id, NEW.empresa, NEW.categoria, NEW.mes, NEW.ano, NEW.valor_orcamento_vigente)
       ON CONFLICT (projeto_id, empresa, categoria, mes, ano)
       DO UPDATE SET
           valor_orcamento = EXCLUDED.valor_orcamento,
           updated_at = CURRENT_TIMESTAMP;
   END IF;
   RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_orcamento_data() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 INSERT INTO controle_orcamento (projeto_id, empresa, categoria, mes, ano, valor_orcamento, valor_pedidos_solicitados, saldo)
 VALUES (NEW.projeto_id, NEW.empresa, NEW.categoria, NEW.mes, NEW.ano, NEW.valor_orcamento, 0, NEW.valor_orcamento);
 RETURN NEW;
END;
$$;

-- Trava de soma das parcelas: le a configuracao de fluxo do projeto do pedido.
CREATE OR REPLACE FUNCTION public.validar_limite_parcelas_pedido() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_pedido  numeric;
  v_projeto integer;
  v_soma    numeric;
BEGIN
  IF NEW.pedido_id IS NULL OR NEW.valor_pagar IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT valor_pedido, projeto_id INTO v_pedido, v_projeto FROM pedidos_solicitados WHERE id = NEW.pedido_id;
  IF v_pedido IS NULL THEN
    RETURN NEW;
  END IF;

  IF (SELECT valor FROM config WHERE chave = 'fluxo_sistema' AND projeto_id = v_projeto LIMIT 1) = '3' THEN
    RETURN NEW;
  END IF;

  SELECT COALESCE(SUM(valor_pagar), 0) INTO v_soma
    FROM controle_pagamentos
   WHERE pedido_id = NEW.pedido_id
     AND id IS DISTINCT FROM NEW.id;

  IF v_soma + NEW.valor_pagar > v_pedido THEN
    RAISE EXCEPTION 'Soma das parcelas (R$ %) excede o valor autorizado do pedido (R$ %).',
      to_char(v_soma + NEW.valor_pagar, 'FM999G999G990D00'), to_char(v_pedido, 'FM999G999G990D00');
  END IF;

  RETURN NEW;
END;
$$;

-- O cronograma sempre herda o projeto do pedido (vale tambem para chamadas de servidor, sem cabecalho).
CREATE FUNCTION public.fluxo_herda_projeto() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  SELECT projeto_id INTO NEW.projeto_id FROM pedidos_solicitados WHERE id = NEW.pedido_id;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trigger_fluxo_herda_projeto
  BEFORE INSERT ON public.pedidos_solicitados_fluxo
  FOR EACH ROW EXECUTE FUNCTION public.fluxo_herda_projeto();

-- Recebimentos
CREATE OR REPLACE FUNCTION public.atualiza_controle_orcamento_receita() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
   INSERT INTO controle_orcamento_receita (projeto_id, empresa, categoria, mes, ano, valor_orcamento)
   VALUES (NEW.projeto_id, NEW.empresa, NEW.categoria, NEW.mes, NEW.ano, NEW.valor_orcamento)
   ON CONFLICT (projeto_id, empresa, categoria, mes, ano)
   DO UPDATE SET valor_orcamento = EXCLUDED.valor_orcamento;
   RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.atualizar_valor_pedidos_solicitados_receita() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE controle_orcamento_receita co
    SET valor_pedidos_solicitados = (
        SELECT COALESCE(SUM(valor_referente), 0)
        FROM pedidos_solicitados_fluxo_receita psf
        WHERE psf.projeto_id = co.projeto_id
          AND psf.empresa = co.empresa
          AND psf.categoria = co.categoria
          AND psf.mes = co.mes
          AND psf.ano = co.ano
          AND psf.status != 'Não Autorizado'
    )
    WHERE EXISTS (
        SELECT 1
        FROM pedidos_solicitados_fluxo_receita psf
        WHERE psf.projeto_id = co.projeto_id
          AND psf.empresa = co.empresa
          AND psf.categoria = co.categoria
          AND psf.mes = co.mes
          AND psf.ano = co.ano
    );

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_valor_pedidos_solicitados_receita() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE controle_orcamento_receita co
  SET valor_pedidos_solicitados = (
    SELECT COALESCE(SUM(psf.valor_referente), 0)
    FROM pedidos_solicitados_fluxo_receita psf
    WHERE psf.projeto_id = co.projeto_id
    AND psf.empresa = co.empresa
    AND psf.categoria = co.categoria
    AND CAST(psf.mes AS INTEGER) = CAST(co.mes AS INTEGER)
    AND CAST(psf.ano AS INTEGER) = CAST(co.ano AS INTEGER)
  )
  WHERE co.projeto_id = NEW.projeto_id
  AND co.empresa = NEW.empresa
  AND co.categoria = NEW.categoria
  AND CAST(co.mes AS INTEGER) = CAST(NEW.mes AS INTEGER)
  AND CAST(co.ano AS INTEGER) = CAST(NEW.ano AS INTEGER);

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_orcamento_analise_receita() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
   registro_existente registro_orcamento_analise_receita%ROWTYPE;
BEGIN
   SELECT * INTO registro_existente
   FROM registro_orcamento_analise_receita
   WHERE projeto_id = NEW.projeto_id
   AND empresa = NEW.empresa
   AND categoria = NEW.categoria
   AND mes = NEW.mes
   AND ano = NEW.ano;

   IF FOUND THEN
       UPDATE registro_orcamento_analise_receita
       SET valor_orcamento_vigente = NEW.valor_orcamento
       WHERE projeto_id = NEW.projeto_id
       AND empresa = NEW.empresa
       AND categoria = NEW.categoria
       AND mes = NEW.mes
       AND ano = NEW.ano;
   ELSE
       INSERT INTO registro_orcamento_analise_receita (
           projeto_id, empresa, categoria, mes, ano, valor_orcamento_vigente, valor_orcamento_inicial
       )
       VALUES (
           NEW.projeto_id, NEW.empresa, NEW.categoria, NEW.mes, NEW.ano, NEW.valor_orcamento, NEW.valor_orcamento
       );
   END IF;

   RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_orcamentos_usuarios_receita() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
   IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
       INSERT INTO orcamentos_usuarios_receita (projeto_id, empresa, categoria, mes, ano, valor_orcamento)
       VALUES (NEW.projeto_id, NEW.empresa, NEW.categoria, NEW.mes, NEW.ano, NEW.valor_orcamento_vigente)
       ON CONFLICT (projeto_id, empresa, categoria, mes, ano)
       DO UPDATE SET
           valor_orcamento = EXCLUDED.valor_orcamento,
           updated_at = CURRENT_TIMESTAMP;
   END IF;
   RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_orcamento_data_receita() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 INSERT INTO controle_orcamento_receita (projeto_id, empresa, categoria, mes, ano, valor_orcamento, valor_pedidos_solicitados, saldo)
 VALUES (NEW.projeto_id, NEW.empresa, NEW.categoria, NEW.mes, NEW.ano, NEW.valor_orcamento, 0, NEW.valor_orcamento);
 RETURN NEW;
END;
$$;

-- Trava de soma das parcelas: le a configuracao de fluxo do projeto do pedido.
CREATE OR REPLACE FUNCTION public.validar_limite_parcelas_pedido_receita() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_pedido  numeric;
  v_projeto integer;
  v_soma    numeric;
BEGIN
  IF NEW.pedido_id IS NULL OR NEW.valor_pagar IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT valor_pedido, projeto_id INTO v_pedido, v_projeto FROM pedidos_solicitados_receita WHERE id = NEW.pedido_id;
  IF v_pedido IS NULL THEN
    RETURN NEW;
  END IF;

  IF (SELECT valor FROM config WHERE chave = 'fluxo_sistema_receita' AND projeto_id = v_projeto LIMIT 1) = '3' THEN
    RETURN NEW;
  END IF;

  SELECT COALESCE(SUM(valor_pagar), 0) INTO v_soma
    FROM controle_recebimento
   WHERE pedido_id = NEW.pedido_id
     AND id IS DISTINCT FROM NEW.id;

  IF v_soma + NEW.valor_pagar > v_pedido THEN
    RAISE EXCEPTION 'Soma das parcelas (R$ %) excede o valor autorizado do pedido (R$ %).',
      to_char(v_soma + NEW.valor_pagar, 'FM999G999G990D00'), to_char(v_pedido, 'FM999G999G990D00');
  END IF;

  RETURN NEW;
END;
$$;

-- O cronograma sempre herda o projeto do pedido (vale tambem para chamadas de servidor, sem cabecalho).
CREATE FUNCTION public.fluxo_herda_projeto_receita() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  SELECT projeto_id INTO NEW.projeto_id FROM pedidos_solicitados_receita WHERE id = NEW.pedido_id;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trigger_fluxo_herda_projeto_receita
  BEFORE INSERT ON public.pedidos_solicitados_fluxo_receita
  FOR EACH ROW EXECUTE FUNCTION public.fluxo_herda_projeto_receita();

-- Filtros de Acompanhar (valores distintos) so do projeto ativo.
CREATE OR REPLACE FUNCTION public.pedidos_solicitados_valores_distintos(coluna text) RETURNS TABLE(valor text) LANGUAGE plpgsql AS $$
BEGIN
  IF coluna = 'empresa' THEN
    RETURN QUERY SELECT DISTINCT empresa FROM pedidos_solicitados WHERE empresa IS NOT NULL AND projeto_id = app_projeto_default() ORDER BY empresa;
  ELSIF coluna = 'categoria' THEN
    RETURN QUERY SELECT DISTINCT categoria FROM pedidos_solicitados WHERE categoria IS NOT NULL AND projeto_id = app_projeto_default() ORDER BY categoria;
  ELSIF coluna = 'fornecedor' THEN
    RETURN QUERY SELECT DISTINCT fornecedor FROM pedidos_solicitados WHERE fornecedor IS NOT NULL AND projeto_id = app_projeto_default() ORDER BY fornecedor;
  ELSE
    RAISE EXCEPTION 'coluna invalida: %', coluna;
  END IF;
END;
$$;

COMMIT;

