-- Extratos bancarios (upload de CSV/OFX/TXT do banco): guarda o cabecalho do extrato
-- (conta + periodo) e os lancamentos. Reimportar o mesmo periodo em outro formato nao duplica:
-- a unicidade e por (projeto_id, conta, periodo_inicio, periodo_fim), nao pelo nome do arquivo.

CREATE TABLE public.extratos_bancarios (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  projeto_id     integer NOT NULL DEFAULT public.app_projeto_default() REFERENCES public.projetos(id),
  conta          text NOT NULL,
  periodo_inicio date NOT NULL,
  periodo_fim    date NOT NULL,
  saldo_inicial  numeric(14,2),
  saldo_final    numeric(14,2),
  formato_origem text NOT NULL CHECK (formato_origem IN ('csv', 'ofx', 'txt')),
  nome_arquivo   text NOT NULL,
  anexo_id       text,
  usuario        character varying(255) NOT NULL,
  criado_em      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (projeto_id, conta, periodo_inicio, periodo_fim)
);

CREATE TABLE public.extratos_bancarios_lancamentos (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  extrato_id    integer NOT NULL REFERENCES public.extratos_bancarios(id) ON DELETE CASCADE,
  data          date NOT NULL,
  descricao     text NOT NULL,
  valor         numeric(14,2) NOT NULL,
  saldo_apos    numeric(14,2),
  codigo_origem text
);

CREATE INDEX extratos_bancarios_lancamentos_extrato_id_idx
  ON public.extratos_bancarios_lancamentos (extrato_id);
